### ISSUE TITLE
Bug in error message capitalisation splitting

### ISSUE THREAD

**Issue by brocksam** [brocksam/pyproprop#24]
```python
Traceback (most recent call last):
  File "match_sprint_sim.py", line 26, in <module>
    standing_lap_forward_simulation = standing_lap_event.initialise_forward_simulation()
  File "/home/peter/live/lapysim/lapysim/event.py", line 594, in initialise_forward_simulation
    return self.event_phases[0]._initialise_event_phase_forward_simulation()
  File "/home/peter/live/lapysim/lapysim/event.py", line 232, in _initialise_event_phase_forward_simulation
    self._initialise_athletes()
  File "/home/peter/live/lapysim/lapysim/event.py", line 248, in _initialise_athletes
    athlete._initialise_dynamics(self)
  File "/home/peter/live/lapysim/lapysim/athlete.py", line 503, in _initialise_dynamics
    rolling_resistance_model = event.settings._instantiate_rolling_model(self.dynamics)
  File "/home/peter/live/lapysim/lapysim/settings.py", line 54, in _instantiate_rolling_model
    dynamics_model.associated_rr_model = self.rolling_resistance_model
  File "/home/peter/anaconda3/envs/lapysim/lib/python3.7/site-packages/pyproprop/processed_property.py", line 85, in prop
    check_options(value)
  File "/home/peter/anaconda3/envs/lapysim/lib/python3.7/site-packages/pyproprop/processed_property.py", line 196, in check_options
    with_preposition=True)
  File "/home/peter/anaconda3/envs/lapysim/lib/python3.7/site-packages/pyproprop/processed_property.py", line 437, in format_for_output
    return format_multiple_items_for_output(items, *args, **kwargs)
  File "/home/peter/anaconda3/envs/lapysim/lib/python3.7/site-packages/pyproprop/processed_property.py", line 469, in format_multiple_items_for_output
    first_word, _ = formatted_items.split(maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by brocksam** [comment]
Closing because was actually fixed by 0.2.0 release.
